"""
Django settings for esg_project project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@$iggm&&$)tmz*z=6b^d5%^2=9pif_p+br7&l=4jfqos)bd71&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# esg_project/settings.py

# esg_project/settings.py

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Saját alkalmazásaink
    'accounts.apps.AccountsConfig',
    'companies.apps.CompaniesConfig',
    'dashboard.apps.DashboardConfig',
    'esgdata.apps.EsgdataConfig',
    'reports.apps.ReportsConfig',
    'notifications.apps.NotificationsConfig',
    'co2calc.apps.Co2CalcConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'esg_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # <<-- Győződj meg róla, hogy ez a sor itt van és helyes
        'APP_DIRS': True, # Ez teszi lehetővé, hogy az app-specifikus templates mappákat is megtalálja
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'esg_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'esg_autoreport_db',  # << Az általad létrehozott ADATBÁZIS NEVE
        'USER': 'esg_user',           # << Az általad létrehozott FELHASZNÁLÓ NÉV
        'PASSWORD': 'Gyorfiati93', # << Az ehhez a felhasználóhoz tartozó JELSZÓ
        'HOST': 'localhost',              # Általában 'localhost' vagy '127.0.0.1'
        'PORT': '5432',                   # Alapértelmezett PostgreSQL port
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'hu'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# === ÚJ/MÓDOSÍTANDÓ RÉSZ KEZDETE ===
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Hozzáadjuk a projekt gyökerében lévő 'static' mappát
]
# === ÚJ/MÓDOSÍTANDÓ RÉSZ VÉGE ===

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# esg_project/settings.py
# ... (a fájl többi része) ...

# Static files (CSS, JavaScript, Images) - ez már valószínűleg ott van
STATIC_URL = 'static/'
# STATICFILES_DIRS = [BASE_DIR / 'static'] # Ha van közös static mappád

# Media files (User-uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' # Vagy os.path.join(BASE_DIR, 'media') régebbi Django verziókban / más stílusban

LOGIN_REDIRECT_URL = '/' # Sikeres bejelentkezés után a főoldalra (dashboard) irányít
LOGOUT_REDIRECT_URL = '/' # Sikeres kijelentkezés után is a főoldalra (dashboard) ir

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'info@g2amarketing.hu' # Vagy bármilyen cím, amit szeretnél feladóként látni