# Generated by Django 4.2.21 on 2025-05-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('co2calc', '0002_populate_activity_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co2calculationinput',
            name='emission_factor',
            field=models.ForeignKey(blank=True, help_text='Válassz egy konkrét faktort a listából, vagy hagyd üresen az automatikus kereséshez.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='co2calc.emissionfactor', verbose_name='Kiválasztott Emissziós Faktor (felülíráshoz)'),
        ),
    ]
