# Generated by Django 4.2.21 on 2025-05-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co2calc', '0003_alter_co2calculationinput_emission_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='allowed_units',
            field=models.CharField(blank=True, help_text='Vesszővel elválasztott lista az engedélyezett mértékegység kulcsokból (pl. kwh,kg,m3). Hagyd üresen, ha az alapértelmezett összes egység engedélyezett.', max_length=255, null=True, verbose_name='Engedélyezett Mértékegységek'),
        ),
    ]
