# Generated by Django 4.2.21 on 2025-05-29 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Adminisztrátor'), ('esg_felelos', 'ESG Felelős'), ('munkavallalo', 'Munkavállaló'), ('tanacsado', 'Tanácsadó'), ('pending', 'Jóváhagyásra vár')], default='pending', max_length=20, verbose_name='Szerepkör')),
                ('primary_questionnaire_type', models.CharField(blank=True, choices=[('', 'Nincs kiválasztva'), ('sztfh_sajat_teljes', 'Saját Vállalat Teljes ESG Kérdőíve (SZTFH)'), ('sztfh_nagyvall_hu_egt_ch', 'Beszállító: Nagyvállalat (HU, EGT, CH)'), ('sztfh_kozepvall_hu_egt_ch', 'Beszállító: Középvállalkozás (HU, EGT, CH)')], help_text='A felhasználó által kiválasztott fő kérdőív/kontextus.', max_length=50, null=True, verbose_name='Elsődleges Kérdőív Típus')),
                ('profile_setup_complete', models.BooleanField(default=False, help_text='Jelzi, hogy a felhasználó elvégezte-e a kezdeti cégadatok megadását.', verbose_name='Profilbeállítás Befejezve')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='companies.companyprofile', verbose_name='Vállalat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Felhasználói Profil',
                'verbose_name_plural': 'Felhasználói Profilok',
            },
        ),
    ]
