# Generated by Django 4.2.21 on 2025-06-30 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Adminisztrátor'), ('esg_felelos', 'ESG Felelős'), ('munkavallalo', 'Munkavállaló'), ('tanacsado', 'Tanácsadó'), ('pending', 'Jóváhagyásra vár')], default='pending', max_length=20, verbose_name='Szerepkör')),
                ('primary_questionnaire_type', models.CharField(blank=True, choices=[('', '--------- Kérjük, válasszon kérdőív típust! ---------'), ('sztfh_sajat_teljes', 'Saját Vállalat Teljes ESG Kérdőíve (SZTFH alapján)'), ('sztfh_nagyvall_hu_egt_ch', 'Beszállító: Nagyvállalat (HU, EGT, CH)'), ('sztfh_kozepvall_hu_egt_ch', 'Beszállító: Középvállalkozás (HU, EGT, CH)'), ('sztfh_kisvall_hu_egt_ch', 'Beszállító: Kisvállalkozás (HU, EGT, CH)'), ('sztfh_mikrovall_hu_egt_ch', 'Beszállító: Mikrovállalkozás (HU, EGT, CH)'), ('sztfh_nagyvall_oecd_non_hu', 'Beszállító: Nagyvállalat (OECD, nem HU/EGT/CH)'), ('sztfh_kozepvall_oecd_non_hu', 'Beszállító: Középvállalkozás (OECD, nem HU/EGT/CH)'), ('sztfh_kisvall_oecd_non_hu', 'Beszállító: Kisvállalkozás (OECD, nem HU/EGT/CH)'), ('sztfh_mikrovall_oecd_non_hu', 'Beszállító: Mikrovállalkozás (OECD, nem HU/EGT/CH)'), ('sztfh_nagyvall_other', 'Beszállító: Nagyvállalat (Egyéb ország)'), ('sztfh_kozepvall_other', 'Beszállító: Középvállalkozás (Egyéb ország)'), ('sztfh_kisvall_other', 'Beszállító: Kisvállalkozás (Egyéb ország)'), ('sztfh_mikrovall_other', 'Beszállító: Mikrovállalkozás (Egyéb ország)')], help_text='A felhasználó által kiválasztott fő kérdőív/kontextus.', max_length=50, null=True, verbose_name='Elsődleges Kérdőív Típus')),
                ('profile_setup_complete', models.BooleanField(default=False, help_text='Jelzi, hogy a felhasználó elvégezte-e a kezdeti cégadatok megadását.', verbose_name='Profilbeállítás Befejezve')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='companies.companyprofile', verbose_name='Vállalat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Felhasználói Profil',
                'verbose_name_plural': 'Felhasználói Profilok',
            },
        ),
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Egyedi Token')),
                ('email', models.EmailField(blank=True, help_text='Ha meg van adva, csak ez az e-mail cím használhatja fel.', max_length=254, null=True, verbose_name='Meghívott E-mail Címe (opcionális)')),
                ('status', models.CharField(choices=[('active', 'Aktív'), ('used', 'Felhasznált'), ('expired', 'Lejárt')], default='active', max_length=10, verbose_name='Státusz')),
                ('expires_at', models.DateTimeField(verbose_name='Lejárati Dátum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozás Ideje')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Utolsó Módosítás')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitation_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta (Admin)')),
            ],
            options={
                'verbose_name': 'Regisztrációs Meghívó Token',
                'verbose_name_plural': 'Regisztrációs Meghívó Tokenek',
                'ordering': ['-created_at'],
            },
        ),
    ]
