# Generated by Django 4.2.21 on 2025-05-31 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Egyedi Token')),
                ('email', models.EmailField(blank=True, help_text='Ha meg van adva, csak ez az e-mail cím használhatja fel.', max_length=254, null=True, verbose_name='Meghívott E-mail Címe (opcionális)')),
                ('status', models.CharField(choices=[('active', 'Aktív'), ('used', 'Felhasznált'), ('expired', 'Lejárt')], default='active', max_length=10, verbose_name='Státusz')),
                ('expires_at', models.DateTimeField(verbose_name='Lejárati Dátum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozás Ideje')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Utolsó Módosítás')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitation_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta (Admin)')),
            ],
            options={
                'verbose_name': 'Regisztrációs Meghívó Token',
                'verbose_name_plural': 'Regisztrációs Meghívó Tokenek',
                'ordering': ['-created_at'],
            },
        ),
    ]
