# Generated by Django 4.2.21 on 2025-05-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyprofile_address_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='primary_questionnaire_type',
            field=models.CharField(blank=True, choices=[('', 'Nincs kiválasztva'), ('sztfh_sajat_teljes', 'Saját Vállalat Teljes ESG Kérdőíve (SZTFH)'), ('sztfh_nagyvall_hu_egt_ch', 'Beszállító: Nagyvállalat (HU, EGT, CH)'), ('sztfh_kozepvall_hu_egt_ch', 'Beszállító: Középvállalkozás (HU, EGT, CH)')], help_text='A felhasználó által kiválasztott fő kérdőív/kontextus.', max_length=50, null=True, verbose_name='Elsődleges Kérdőív Típus'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_setup_complete',
            field=models.BooleanField(default=False, help_text='Jelzi, hogy a felhasználó elvégezte-e a kezdeti cégadatok megadását.', verbose_name='Profilbeállítás Befejezve'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='companies.companyprofile', verbose_name='Vállalat'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Adminisztrátor'), ('esg_felelos', 'ESG Felelős'), ('munkavallalo', 'Munkavállaló'), ('tanacsado', 'Tanácsadó'), ('pending', 'Jóváhagyásra vár')], default='pending', max_length=20, verbose_name='Szerepkör'),
        ),
    ]
