# Generated by Django 4.2.21 on 2025-05-26 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('annual', 'Éves'), ('quarterly', 'Negyedéves'), ('monthly', 'Havi')], max_length=20, verbose_name='Jelentés Típusa')),
                ('period_year', models.IntegerField(verbose_name='Jelentési Év')),
                ('period_quarter_or_month', models.IntegerField(blank=True, help_text='Negyedéves (1-4) vagy havi (1-12) jelentés esetén', null=True, verbose_name='Jelentési Negyedév/Hónap')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Kérvényezés Ideje')),
                ('status', models.CharField(choices=[('requested', 'Kérvényezve'), ('processing', 'Folyamatban'), ('completed', 'Elkészült'), ('error', 'Hiba')], default='requested', max_length=20, verbose_name='Státusz')),
                ('generated_pdf_path', models.FileField(blank=True, null=True, upload_to='generated_reports/pdf/%Y/%m/', verbose_name='Generált PDF elérési útja')),
                ('generated_excel_path', models.FileField(blank=True, null=True, upload_to='generated_reports/excel/%Y/%m/', verbose_name='Generált Excel elérési útja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Utolsó Módosítás')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_requests', to='companies.companyprofile', verbose_name='Vállalat')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Kérvényezte')),
            ],
            options={
                'verbose_name': 'Jelentésgenerálási Kérés',
                'verbose_name_plural': 'Jelentésgenerálási Kérések',
                'ordering': ['-requested_at'],
            },
        ),
    ]
