# Generated by Django 4.2.21 on 2025-05-29 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TEORCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Pl. 01.11, 62.01', max_length=10, unique=True, verbose_name='TEÁOR Kód')),
                ('name', models.CharField(max_length=255, verbose_name='TEÁOR Megnevezés')),
            ],
            options={
                'verbose_name': 'TEÁOR Kód',
                'verbose_name_plural': 'TEÁOR Kódok',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Vállalat neve')),
                ('industry_old_char', models.CharField(blank=True, max_length=255, null=True, verbose_name='Iparág (Régi Szöveges)')),
                ('address_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ország')),
                ('address_postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Irányítószám')),
                ('address_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Város')),
                ('address_street_and_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Utca, házszám, emelet, ajtó stb.')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adószám')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cégjegyzékszám')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.teorcode', verbose_name='Iparág (TEÁOR)')),
            ],
            options={
                'verbose_name': 'Vállalati Profil',
                'verbose_name_plural': 'Vállalati Profilok',
                'ordering': ['name'],
            },
        ),
    ]
