# Generated by Django 4.2.21 on 2025-05-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESGDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Egyedi azonosító kód, pl. E1-EnergyConsumption', max_length=100, unique=True, verbose_name='Adatpont Kódja')),
                ('name', models.CharField(help_text='Az adatpont olvasható neve, pl. Teljes energiafogyasztás', max_length=255, verbose_name='Adatpont Neve')),
                ('esrs_reference', models.CharField(blank=True, help_text='Kapcsolódó ESRS standard, pl. ESRS E1-6', max_length=50, null=True, verbose_name='ESRS Hivatkozás')),
                ('category', models.CharField(choices=[('environmental', 'Környezeti'), ('social', 'Társadalmi'), ('governance', 'Irányítási')], max_length=20, verbose_name='Kategória')),
                ('data_type', models.CharField(choices=[('number', 'Szám'), ('text', 'Szöveg'), ('date', 'Dátum'), ('file', 'Fájl'), ('boolean', 'Logikai (Igen/Nem)')], max_length=20, verbose_name='Adattípus')),
                ('unit', models.CharField(blank=True, help_text='Pl. kWh, m3, tCO2e, fő, óra', max_length=50, null=True, verbose_name='Mértékegység')),
                ('description', models.TextField(blank=True, help_text='Rövid magyarázat vagy segítség az adatponthoz.', null=True, verbose_name='Leírás/Segítség')),
                ('is_required_for_basic_report', models.BooleanField(default=True, verbose_name='Kötelező az alapjelentéshez?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
            ],
            options={
                'verbose_name': 'ESG Adatpont Definíció',
                'verbose_name_plural': 'ESG Adatpont Definíciók',
                'ordering': ['category', 'code'],
            },
        ),
    ]
