# Generated by Django 4.2.21 on 2025-05-29 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESGDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_version', models.CharField(db_index=True, help_text="Azonosító, melyik SZTFH kérdőívből származik, pl. 'kozepvall_hu_egt_ch_v1'", max_length=100, verbose_name='Kérdőív Verzió Azonosító')),
                ('question_number', models.CharField(db_index=True, max_length=30, verbose_name='Kérdés Sorszáma')),
                ('question_text', models.TextField(verbose_name='Kérdés Szövege')),
                ('pillar', models.CharField(choices=[('environmental', 'Környezeti (E)'), ('social', 'Társadalmi (S)'), ('governance', 'Irányítási (G)'), ('general', 'Általános/Bevezető')], max_length=20, verbose_name='ESG Pillér')),
                ('esrs_topic_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='ESRS Topic Standard')),
                ('esrs_datapoint_definition', models.CharField(blank=True, max_length=100, null=True, verbose_name='ESRS Adatpont Definíció')),
                ('guidance', models.TextField(blank=True, null=True, verbose_name='Útmutató/Megjegyzés')),
                ('is_voluntary', models.BooleanField(default=False, verbose_name='Önkéntes')),
                ('unit_of_measure', models.CharField(blank=True, max_length=100, null=True, verbose_name='Elvárt Mértékegység')),
                ('response_data_type', models.CharField(choices=[('text_long', 'Hosszú szöveges válasz'), ('text_short', 'Rövid szöveges válasz'), ('number', 'Szám'), ('year', 'Évszám'), ('percentage', 'Százalék'), ('currency_eur', 'Pénznem (EUR)'), ('currency_huf', 'Pénznem (HUF)'), ('date', 'Dátum'), ('boolean', 'Igen/Nem'), ('dropdown', 'Legördülő lista'), ('file', 'Fájl feltöltés')], default='text_long', max_length=30, verbose_name='Válasz Adattípusa')),
                ('choice_option_group', models.CharField(blank=True, help_text="Azonosító a 'Legördülő lista' Excelből, ha a válasz típusa 'Legördülő'.", max_length=100, null=True, verbose_name='Legördülő Lista Csoportkulcsa')),
                ('applies_to_questionnaire_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kérdőív Típus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ESG Kérdés (Adatpont)',
                'verbose_name_plural': 'ESG Kérdések (Adatpontok)',
                'ordering': ['questionnaire_version', 'question_number'],
                'unique_together': {('questionnaire_version', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Opció Szövege')),
                ('group_identifier', models.CharField(db_index=True, help_text="Azonosító a 'Legördülő lista' Excelből, ami összeköti ezt az opciócsoportot a releváns ESG adatponttal.", max_length=100, verbose_name='Opciócsoport Azonosító (SZTFH)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Válaszlehetőség (Kérdőívhez)',
                'verbose_name_plural': 'Válaszlehetőségek (Kérdőívhez)',
                'ordering': ['group_identifier', 'text'],
                'unique_together': {('group_identifier', 'text')},
            },
        ),
        migrations.CreateModel(
            name='CompanyDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField(verbose_name='Év')),
                ('period_month', models.IntegerField(blank=True, help_text='Havi vagy negyedéves adatokhoz (1-12)', null=True, verbose_name='Hónap (opcionális)')),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Számszerű érték')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='Szöveges érték')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Dátum érték')),
                ('value_file', models.FileField(blank=True, null=True, upload_to='esg_data_files/%Y/%m/', verbose_name='Fájl érték')),
                ('source_description', models.TextField(blank=True, null=True, verbose_name='Adatforrás leírása')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='Rögzítés dátuma')),
                ('status', models.CharField(choices=[('missing', 'Hiányzó'), ('filled', 'Kitöltött'), ('verified', 'Ellenőrzött')], default='missing', max_length=15, verbose_name='Státusz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva (rendszer)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva (rendszer)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='companies.companyprofile', verbose_name='Vállalat')),
                ('data_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='esgdata.esgdatapoint', verbose_name='ESG Adatpont')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Rögzítette')),
            ],
            options={
                'verbose_name': 'Vállalati ESG Adatbevitel',
                'verbose_name_plural': 'Vállalati ESG Adatbevitelek',
                'ordering': ['-period_year', '-period_month', 'company', 'data_point'],
                'unique_together': {('company', 'data_point', 'period_year', 'period_month')},
            },
        ),
    ]
