# Generated by Django 4.2.21 on 2025-05-25 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esgdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField(verbose_name='Év')),
                ('period_month', models.IntegerField(blank=True, help_text='Havi vagy negyedéves adatokhoz (1-12)', null=True, verbose_name='Hónap (opcionális)')),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Számszerű érték')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='Szöveges érték')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Dátum érték')),
                ('value_file', models.FileField(blank=True, null=True, upload_to='esg_data_files/%Y/%m/', verbose_name='Fájl érték')),
                ('source_description', models.TextField(blank=True, null=True, verbose_name='Adatforrás leírása')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='Rögzítés dátuma')),
                ('status', models.CharField(choices=[('missing', 'Hiányzó'), ('filled', 'Kitöltött'), ('verified', 'Ellenőrzött')], default='missing', max_length=15, verbose_name='Státusz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva (rendszer)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva (rendszer)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='companies.companyprofile', verbose_name='Vállalat')),
                ('data_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='esgdata.esgdatapoint', verbose_name='ESG Adatpont')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Rögzítette')),
            ],
            options={
                'verbose_name': 'Vállalati ESG Adatbevitel',
                'verbose_name_plural': 'Vállalati ESG Adatbevitelek',
                'ordering': ['-period_year', '-period_month', 'company', 'data_point'],
                'unique_together': {('company', 'data_point', 'period_year', 'period_month')},
            },
        ),
    ]
