# Generated by Django 4.2.21 on 2025-05-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esgdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydataentry',
            name='status',
            field=models.CharField(choices=[('missing', 'Hiányzó'), ('in_progress', 'Folyamatban'), ('filled', 'Kitöltött'), ('verified', 'Ellenőrzött')], default='missing', max_length=15, verbose_name='Státusz'),
        ),
    ]
