# Generated by Django 4.2.21 on 2025-07-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esgdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgdatapoint',
            name='available_options',
            field=models.ManyToManyField(blank=True, to='esgdata.choiceoption', verbose_name='Válaszlehetőségek'),
        ),
    ]
