# Generated by Django 4.2.21 on 2025-05-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esgdata', '0002_companydataentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esgdatapoint',
            options={'ordering': ['question_number', 'question_text'], 'verbose_name': 'ESG Adatpont (Kérdés)', 'verbose_name_plural': 'ESG Adatpontok (Kérdések)'},
        ),
        migrations.RemoveField(
            model_name='esgdatapoint',
            name='category',
        ),
        migrations.RemoveField(
            model_name='esgdatapoint',
            name='code',
        ),
        migrations.RemoveField(
            model_name='esgdatapoint',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='esgdatapoint',
            name='description',
        ),
        migrations.RemoveField(
            model_name='esgdatapoint',
            name='esrs_reference',
        ),
        migrations.RemoveField(
            model_name='esgdatapoint',
            name='is_required_for_basic_report',
        ),
        migrations.RemoveField(
            model_name='esgdatapoint',
            name='name',
        ),
        migrations.RemoveField(
            model_name='esgdatapoint',
            name='unit',
        ),
        migrations.AddField(
            model_name='esgdatapoint',
            name='applies_to_questionnaire_type',
            field=models.CharField(blank=True, db_index=True, help_text='Pl. középváll_hu_egt_sv, nagyváll_egyeb. Vesszővel elválasztva több is lehet.', max_length=100, null=True, verbose_name='Releváns Kérdőív Típus(ok)'),
        ),
        migrations.AddField(
            model_name='esgdatapoint',
            name='choice_option_group',
            field=models.CharField(blank=True, help_text="A 'Válaszlehetőségek' táblában lévő csoportazonosító, ha a válasz típusa 'Legördülő'.", max_length=100, null=True, verbose_name='Válaszlehetőség Csoport Azonosító'),
        ),
        migrations.AddField(
            model_name='esgdatapoint',
            name='esrs_datapoint_definition',
            field=models.CharField(blank=True, help_text='Az ESRS által definiált adatpont azonosítója, ha van.', max_length=100, null=True, verbose_name='ESRS Adatpont Kód (pl. DR, AR)'),
        ),
        migrations.AddField(
            model_name='esgdatapoint',
            name='esrs_topic_standard',
            field=models.CharField(blank=True, help_text='Pl. ESRS E1, ESRS S1, ESRS G1', max_length=100, null=True, verbose_name='Kapcsolódó ESRS Topic Standard'),
        ),
        migrations.AddField(
            model_name='esgdatapoint',
            name='guidance',
            field=models.TextField(blank=True, null=True, verbose_name='Útmutató / Megjegyzés a kitöltéshez'),
        ),
        migrations.AddField(
            model_name='esgdatapoint',
            name='is_voluntary',
            field=models.BooleanField(default=False, verbose_name='Önkéntes Megválaszolású?'),
        ),
        migrations.AddField(
            model_name='esgdatapoint',
            name='pillar',
            field=models.CharField(choices=[('environmental', 'Környezeti (E)'), ('social', 'Társadalmi (S)'), ('governance', 'Irányítási (G)'), ('general', 'Általános')], default='general', max_length=20, verbose_name='ESG Pillér'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esgdatapoint',
            name='question_number',
            field=models.CharField(db_index=True, default='temp_qn', help_text='Pl. Á.1.1.a, K.2.1', max_length=30, verbose_name='Kérdés Sorszáma (kérdőívben)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esgdatapoint',
            name='question_text',
            field=models.TextField(default='Ideiglenes kérdésszöveg', verbose_name='Kérdés Szövege / Adatpont Leírása'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esgdatapoint',
            name='response_data_type',
            field=models.CharField(choices=[('text', 'Szöveges kifejtés'), ('number', 'Szám'), ('date', 'Dátum'), ('boolean', 'Igen/Nem (Logikai)'), ('dropdown', 'Legördülő lista (Választás)'), ('file', 'Fájl feltöltés')], default='text', max_length=20, verbose_name='Válasz Adattípusa'),
        ),
        migrations.AddField(
            model_name='esgdatapoint',
            name='unit_of_measure',
            field=models.CharField(blank=True, help_text='Ha a válasz numerikus, pl. EUR, Fő, óra, kWh, tonna, m3', max_length=50, null=True, verbose_name='Elvárt Mértékegység'),
        ),
        migrations.AlterField(
            model_name='esgdatapoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='esgdatapoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Opció Szövege')),
                ('group_identifier', models.CharField(blank=True, db_index=True, help_text='Azonosító, ami összeköti ezt az opciót a releváns ESG adatponttal (pl. kérdőívben használt lista neve).', max_length=100, null=True, verbose_name='Opciócsoport Azonosító')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Válaszlehetőség',
                'verbose_name_plural': 'Válaszlehetőségek',
                'ordering': ['group_identifier', 'text'],
                'unique_together': {('group_identifier', 'text')},
            },
        ),
    ]
