# Generated by Django 4.2.21 on 2025-05-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esgdata', '0002_alter_companydataentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgdatapoint',
            name='pillar',
            field=models.CharField(choices=[('environmental', 'Környezeti (E)'), ('social', 'Társadalmi (S)'), ('governance', 'Irányítási (G)'), ('datasheet', 'Általános Vállalati Adatlap'), ('ghg_targets', 'ÜHG Emissziós Célok'), ('general', 'Egyéb Általános Adatok')], max_length=20, verbose_name='ESG Pillér / Témakör'),
        ),
    ]
