# Generated by Django 4.2.21 on 2025-05-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esgdata', '0003_alter_esgdatapoint_pillar'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgdatapoint',
            name='adatlap_kontextus',
            field=models.CharField(blank=True, choices=[('altalanos', 'Általános (nem specifikus)'), ('sajat', 'Saját Jelentő Adatlapja'), ('beszallito', 'Beszállítói Adatlap')], default='altalanos', max_length=20, null=True, verbose_name='Adatlap Kontextusa'),
        ),
        migrations.AlterField(
            model_name='esgdatapoint',
            name='pillar',
            field=models.CharField(choices=[('environmental', 'Környezeti (E)'), ('social', 'Társadalmi (S)'), ('governance', 'Irányítási (G)'), ('datasheet', 'Általános Vállalati Adatlap'), ('ghg_targets', 'ÜHG Emissziós Célok'), ('general', 'Egyéb Általános Adatok')], max_length=20, verbose_name='Jelentésrész Kiválasztása'),
        ),
    ]
