# Generated by Django 4.2.21 on 2025-06-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esgdata', '0004_esgdatapoint_adatlap_kontextus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgdatapoint',
            name='placeholder_text',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Placeholder szöveg az input mezőhöz'),
        ),
    ]
