# Generated by Django 4.2.21 on 2025-05-29 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Üzenet')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Határidő')),
                ('is_read', models.BooleanField(default=False, verbose_name='Elolvasva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Értesítés',
                'verbose_name_plural': 'Értesítések',
                'ordering': ['-created_at'],
            },
        ),
    ]
